{
  "formatVersion": "1.1",
  "component": {
    "group": "org.coralprotocol.payment",
    "module": "blockchain",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "blockchain-0.0.1.jar",
          "url": "blockchain-0.0.1.jar",
          "size": 918795,
          "sha512": "c69a0bce4f78927c9c68ce7e0244990860bfa35d497e3a7b37719432c0e0394b80c0d32d9559fb4ac4b50832c7fdd2c9666e87c923cf9d61b15a9eab8f59a913",
          "sha256": "33bbdafdf88be50694bed90bf9925372f409b5ba2cfedc67109145a589b71115",
          "sha1": "f63cc4d80ac6e0651bba90658fb93133b62024b0",
          "md5": "980e50085e931341540766fb1a4af659"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.25.1"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-kotlin",
          "version": {
            "requires": "3.25.1"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.14.0"
          }
        },
        {
          "group": "io.github.microutils",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "3.0.5"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.4.14"
          }
        },
        {
          "group": "org.bitcoinj",
          "module": "bitcoinj-core",
          "version": {
            "requires": "0.16.2"
          }
        }
      ],
      "files": [
        {
          "name": "blockchain-0.0.1.jar",
          "url": "blockchain-0.0.1.jar",
          "size": 918795,
          "sha512": "c69a0bce4f78927c9c68ce7e0244990860bfa35d497e3a7b37719432c0e0394b80c0d32d9559fb4ac4b50832c7fdd2c9666e87c923cf9d61b15a9eab8f59a913",
          "sha256": "33bbdafdf88be50694bed90bf9925372f409b5ba2cfedc67109145a589b71115",
          "sha1": "f63cc4d80ac6e0651bba90658fb93133b62024b0",
          "md5": "980e50085e931341540766fb1a4af659"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "blockchain-0.0.1-all.jar",
          "url": "blockchain-0.0.1-all.jar",
          "size": 35966350,
          "sha512": "e9f58ea2fd75dd28f8076b612d2d5b90b0b9fef0ad80ba1f48f536ce7ee7397f3fa54b01c5dd9f4363baca10c28172ea283dbec707940476ae0a3160c8825e6d",
          "sha256": "09be5b8645c8d13b12718158ea7273ef73ae8817af1576ff5bc0d951993feb1e",
          "sha1": "82550e2601cd003d4d07323fdc949b8cee754e10",
          "md5": "dba0f62d6c0e3b380721f49886aec8d9"
        }
      ]
    }
  ]
}
