{
  "formatVersion": "1.1",
  "component": {
    "group": "org.coralprotocol.payment",
    "module": "blockchain",
    "version": "0.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "blockchain-0.0.6.jar",
          "url": "blockchain-0.0.6.jar",
          "size": 1292352,
          "sha512": "7c9969f9d61084c08e4acea1f5c1fc930caad5181db0138ff3f4817345b34417a1f16de03ec48dd22582982ab268c8221e1a9bb4676582f313dd299895824d5e",
          "sha256": "97cafa32cd5432a79a02b7a33aa422a7cc1ad3fdd3a3345affe7825a74ccbd06",
          "sha1": "e6fd06a6cef57ccd4dbfa43afb265806d9382f98",
          "md5": "db7babcd6c194f5cf951209b8df3b79c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.25.1"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-kotlin",
          "version": {
            "requires": "3.25.1"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.14.0"
          }
        },
        {
          "group": "io.github.microutils",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "3.0.5"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.4.14"
          }
        },
        {
          "group": "org.bitcoinj",
          "module": "bitcoinj-core",
          "version": {
            "requires": "0.16.2"
          }
        }
      ],
      "files": [
        {
          "name": "blockchain-0.0.6.jar",
          "url": "blockchain-0.0.6.jar",
          "size": 1292352,
          "sha512": "7c9969f9d61084c08e4acea1f5c1fc930caad5181db0138ff3f4817345b34417a1f16de03ec48dd22582982ab268c8221e1a9bb4676582f313dd299895824d5e",
          "sha256": "97cafa32cd5432a79a02b7a33aa422a7cc1ad3fdd3a3345affe7825a74ccbd06",
          "sha1": "e6fd06a6cef57ccd4dbfa43afb265806d9382f98",
          "md5": "db7babcd6c194f5cf951209b8df3b79c"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "blockchain-0.0.6-all.jar",
          "url": "blockchain-0.0.6-all.jar",
          "size": 36671213,
          "sha512": "ad5873552e5cef4bf1564566508ccb17c0d9ce267c17fd65ef41ce0d4b0a670956e7bd088a90ad3f91075024098513d933540b5a48a3d7a7fe0afb0c0176c41a",
          "sha256": "4ecd624c9e07cf3c34bac19bda1c9c1c8da72066ec5ef104b3c5906492f7dcc5",
          "sha1": "0efaa420e861ed05366762aafd97474ba0bfe975",
          "md5": "cfd2e5fd72ad28e2732f3fe6ca459dae"
        }
      ]
    }
  ]
}
