{
  "formatVersion": "1.1",
  "component": {
    "group": "org.coralprotocol.payment",
    "module": "blockchain",
    "version": "0.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "blockchain-0.0.3.jar",
          "url": "blockchain-0.0.3.jar",
          "size": 896406,
          "sha512": "0840a8bd40b592105c7857229c61ca2229e542b2a3834f558a7d47e51e28b3b988c62d6126c70364c13e84e86bc0a578b6d97621cb535f2e9871c86f42520521",
          "sha256": "7c38096f7928a75416819e9d957656902cbe01830be1863ccb678e93c0af6573",
          "sha1": "a6c8f83ecac18c4823cc83ea3ba856becdbebb64",
          "md5": "0e067dba70c93faa4632c0b599097ed8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.25.1"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-kotlin",
          "version": {
            "requires": "3.25.1"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.14.0"
          }
        },
        {
          "group": "io.github.microutils",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "3.0.5"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.4.14"
          }
        },
        {
          "group": "org.bitcoinj",
          "module": "bitcoinj-core",
          "version": {
            "requires": "0.16.2"
          }
        }
      ],
      "files": [
        {
          "name": "blockchain-0.0.3.jar",
          "url": "blockchain-0.0.3.jar",
          "size": 896406,
          "sha512": "0840a8bd40b592105c7857229c61ca2229e542b2a3834f558a7d47e51e28b3b988c62d6126c70364c13e84e86bc0a578b6d97621cb535f2e9871c86f42520521",
          "sha256": "7c38096f7928a75416819e9d957656902cbe01830be1863ccb678e93c0af6573",
          "sha1": "a6c8f83ecac18c4823cc83ea3ba856becdbebb64",
          "md5": "0e067dba70c93faa4632c0b599097ed8"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "blockchain-0.0.3-all.jar",
          "url": "blockchain-0.0.3-all.jar",
          "size": 35942927,
          "sha512": "ef3a49ed7ce4aeed0e42ee8e20471b4e126d804a034f7ef7f64694637acd20b31716b43877edadf5a8c9faf3dcaf7842075984131a37068962faaa435e0a96c0",
          "sha256": "c793a0f23dfd3bc43e10b9ada0d05f4c9e71d5257715c44b03094a1d96977977",
          "sha1": "a892e68e301a3c07311262fb6653fc8f7b701e69",
          "md5": "40914b856b65506023cec5ca86d25f9c"
        }
      ]
    }
  ]
}
