{
  "formatVersion": "1.1",
  "component": {
    "group": "org.coralprotocol.payment",
    "module": "blockchain",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "blockchain-0.1.0.jar",
          "url": "blockchain-0.1.0.jar",
          "size": 1292632,
          "sha512": "63a5ddbc8d3b44ff735cfa245cac812de5e562e2fc807040fae5a1cd578610548bf67476360d77f79ee6f3a3ac565cb2addf9f95b9545f325bd90e92944bedab",
          "sha256": "51e026a95690b9c5540ad339912c3984a9e6c790bf82c6aede3eadf11518b943",
          "sha1": "8f730760ebb2be27d4066f406b9950f03430df0b",
          "md5": "cf090dac69a902c8bde3ef9ceec88cb1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.25.1"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-kotlin",
          "version": {
            "requires": "3.25.1"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.14.0"
          }
        },
        {
          "group": "io.github.microutils",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "3.0.5"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.4.14"
          }
        },
        {
          "group": "org.bitcoinj",
          "module": "bitcoinj-core",
          "version": {
            "requires": "0.16.2"
          }
        }
      ],
      "files": [
        {
          "name": "blockchain-0.1.0.jar",
          "url": "blockchain-0.1.0.jar",
          "size": 1292632,
          "sha512": "63a5ddbc8d3b44ff735cfa245cac812de5e562e2fc807040fae5a1cd578610548bf67476360d77f79ee6f3a3ac565cb2addf9f95b9545f325bd90e92944bedab",
          "sha256": "51e026a95690b9c5540ad339912c3984a9e6c790bf82c6aede3eadf11518b943",
          "sha1": "8f730760ebb2be27d4066f406b9950f03430df0b",
          "md5": "cf090dac69a902c8bde3ef9ceec88cb1"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "blockchain-0.1.0-all.jar",
          "url": "blockchain-0.1.0-all.jar",
          "size": 36682331,
          "sha512": "6534aefc8ff547c25c664c0e67a045552122ab1743be66a7e90f224344c9087e1deca6db696d09a1c4ee9b27f3396162a5bec244726021651c5caaa3e25c5c79",
          "sha256": "d0fdd6dd8cf60188bfe9f09dc0ad4b46f7ed34026fee2ed09c8801bdbca52157",
          "sha1": "4b16e835e1b79df3328fe966e327300a6315a18e",
          "md5": "288e0dc611cd45d4a70a1e25d8e6b2a5"
        }
      ]
    }
  ]
}
